#!/bin/sh
#
# Copyright (C) 2017 TDT GmbH
#
# This is free software, licensed under the GNU General Public License v2.
# See https://www.gnu.org/licenses/gpl-2.0.txt for more information.
#
########################################################################

. /lib/functions.sh
. /lib/functions/network.sh
. /usr/share/libubox/jshn.sh

log() {
logger -p daemon.debug -t "Skript" "$1"
}

# Einlesen der Alarmstates (beim booten ist der Status 0)
alarmstate_wan=$(uci_get_state network wan alarmstate 0)
alarmstate_wwan=$(uci_get_state network wwan alarmstate 0)
alarmstate_xdsl=$(uci_get_state network xdsl alarmstate 0)



### WAN - Events bei WAN up & down ####################################
if [ "${ACTION}" = "ifup" ] && [ "${INTERFACE}" = "wan" ]
then
		if [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 1 ]
			then
				uci_toggle_state network wan alarmstate 0					
				/etc/init.d/./wwan_leds start
				/etc/init.d/./led reload
			        log "WAN UP - Interface WAN ist up"
			        log "WAN Alarm LED off"
                                log "Keine Verbindungsfehler mehr vorhanden"
		elif [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 0 ]
			then
				exit
		else
				uci_toggle_state network wan alarmstate 0
				echo '0' > /sys/class/leds/led1/brightness
			        log "xDSL UP - Interface xDSL ist up"
			        log "xDSL Alarm LED off"
                                log "ES SIND NOCH VERBINDUNGSFEHLER VORHANDEN!"
		fi
fi

if [ "${ACTION}" = "ifdown" ] && [ "${INTERFACE}" = "wan" ]
then
		if [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 0 ]
			then
				uci_toggle_state network wan alarmstate 1
				/etc/init.d/./wwan_leds stop
				sleep 5s
				echo '0' > /sys/class/leds/led0/brightness
				echo '255' > /sys/class/leds/led1/brightness
				echo '0' > /sys/class/leds/led2/brightness
				echo '0' > /sys/class/leds/led3/brightness
				echo '0' > /sys/class/leds/led4/brightness
				echo '0' > /sys/class/leds/led5/brightness
				echo '0' > /sys/class/leds/led6/brightness
				echo '255' > /sys/class/leds/led7/brightness
				echo '0' > /sys/class/leds/led8/brightness
			        log "WAN DOWN - Interface WAN ist down"
			        log "WAN Alarm LED on"
				log "Keine weiteren Interfaces mit Fehler"
		else
				uci_toggle_state network wan alarmstate 1
				echo '255' > /sys/class/leds/led1/brightness
			        log "WAN DOWN - Interface xDSL ist down"
			        log "WAN Alarm LED on"
				log "WEITERE INTERFACES MIT FEHLERN VORHANDEN!"
		fi
fi
#-----------------------------------------------------------------------



### XDSL - Events bei xDSL up & down ####################################
if [ "${ACTION}" = "ifup" ] && [ "${INTERFACE}" = "xdsl" ]
then
		if [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 1 ] && [ "$alarmstate_wan" = 0 ]
			then
				uci_toggle_state network xdsl alarmstate 0					
				/etc/init.d/./wwan_leds start
				/etc/init.d/./led reload
			        log "xDSL UP - Interface xDSL ist up"
			        log "xDSL Alarm LED off"
                                log "Keine Verbindungsfehler mehr vorhanden"
		elif [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 0 ]
			then
				exit
		else
				uci_toggle_state network xdsl alarmstate 0
				echo '0' > /sys/class/leds/led8/brightness
			        log "xDSL UP - Interface xDSL ist up"
			        log "xDSL Alarm LED off"
                                log "ES SIND NOCH VERBINDUNGSFEHLER VORHANDEN!"
		fi
fi

if [ "${ACTION}" = "ifdown" ] && [ "${INTERFACE}" = "xdsl" ]
then
		if [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 0 ]
			then
				uci_toggle_state network xdsl alarmstate 1
				/etc/init.d/./wwan_leds stop
				sleep 5s
				echo '0' > /sys/class/leds/led0/brightness
				echo '0' > /sys/class/leds/led1/brightness
				echo '0' > /sys/class/leds/led2/brightness
				echo '0' > /sys/class/leds/led3/brightness
				echo '0' > /sys/class/leds/led4/brightness
				echo '0' > /sys/class/leds/led5/brightness
				echo '0' > /sys/class/leds/led6/brightness
				echo '255' > /sys/class/leds/led7/brightness
				echo '255' > /sys/class/leds/led8/brightness
			        log "xDSL DOWN - Interface xDSL ist down"
			        log "xDSL Alarm LED on"
				log "Keine weiteren Interfaces mit Fehler"
		else
				uci_toggle_state network xdsl alarmstate 1
				echo '255' > /sys/class/leds/led8/brightness
			        log "xDSL DOWN - Interface xDSL ist down"
			        log "xDSL Alarm LED on"
				log "WEITERE INTERFACES MIT FEHLERN VORHANDEN!"
		fi
fi
#-----------------------------------------------------------------------




### WWAN - Events bei WWAN (LTE) up & down ####################################
if [ "${ACTION}" = "ifup" ] && [ "${INTERFACE}" = "wwan" ]
then
		if [ "$alarmstate_wwan" = 1 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 0 ]
			then
				uci_toggle_state network wwan alarmstate 0					
				/etc/init.d/./wwan_leds start
				/etc/init.d/./led reload
			        log "WWAN UP - Interface WWAN ist up"
			        log "WWAN Alarm LED off"
                                log "Keine Verbindungsfehler mehr vorhanden"
		elif [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 0 ]
			then
				exit
		else
				uci_toggle_state network wwan alarmstate 0
				echo '0' > /sys/class/leds/led3/brightness
			        log "WWAN UP - Interface WWAN ist up"
			        log "WWAN Alarm LED off"
                                log "ES SIND NOCH VERBINDUNGSFEHLER VORHANDEN!"
		fi
fi

if [ "${ACTION}" = "ifdown" ] && [ "${INTERFACE}" = "wwan" ]
then
		if [ "$alarmstate_wwan" = 0 ] && [ "$alarmstate_xdsl" = 0 ] && [ "$alarmstate_wan" = 0 ]
			then
				uci_toggle_state network wwan alarmstate 1
				/etc/init.d/./wwan_leds stop
				sleep 5s
				echo '0' > /sys/class/leds/led0/brightness
				echo '0' > /sys/class/leds/led1/brightness
				echo '0' > /sys/class/leds/led2/brightness
				echo '255' > /sys/class/leds/led3/brightness
				echo '0' > /sys/class/leds/led4/brightness
				echo '0' > /sys/class/leds/led5/brightness
				echo '0' > /sys/class/leds/led6/brightness
				echo '255' > /sys/class/leds/led7/brightness
				echo '0' > /sys/class/leds/led8/brightness
			        log "WWAN DOWN - Interface WWAN ist down"
			        log "WWAN Alarm LED on"
				log "Keine weiteren Interfaces mit Fehler"
		else
				uci_toggle_state network wwan alarmstate 1
				echo '255' > /sys/class/leds/led3/brightness
			        log "WWAN DOWN - Interface WWAN ist down"
			        log "WWAN Alarm LED on"
				log "WEITERE INTERFACES MIT FEHLERN VORHANDEN!"
		fi
fi
#-----------------------------------------------------------------------

