#!/bin/sh
#
# Copyright (C) 2017 TDT GmbH
#
# This is free software, licensed under the GNU General Public License v2.
# See https://www.gnu.org/licenses/gpl-2.0.txt for more information.
#
########################################################################

. /lib/functions.sh
. /lib/functions/network.sh
. /usr/share/libubox/jshn.sh

log() {
logger -p daemon.debug -t "Skript" "$1"
}

# Einlesen der Alarmstates
alarmstate_wan=$(uci_get_state network wan alarmstate 0)
alarmstate_wwan=$(uci_get_state network wwan alarmstate 0)
alarmstate_xdsl=$(uci_get_state network xdsl alarmstate 0)


case $1 in
 reset)
 uci_toggle_state network wan alarmstate 0
 uci_toggle_state network xdsl alarmstate 0 
 uci_toggle_state network wwan alarmstate 0
 /etc/init.d/./wwan_leds start
 /etc/init.d/./led reload
 log "ALARMSTATES MANUELL ZURUECKGESETZT!"
 ;;
 status)
 echo "Alarmstatus WAN:" $alarmstate_wan
 echo "Alarmstatus WWAN:" $alarmstate_wwan
 echo "Alarmstatus DSL:" $alarmstate_xdsl
 ;;
esac
